### ISSUE TITLE
Cannot insert data when retentionPolicy is specified

### ISSUE THREAD

**Issue by jaka** [node-influx/node-influx#288] opened 2017-08-14 16:17 UTC
I'm using Debian Jessie with InfluxDB 1.3.2 and Nodejs v6.11.2 and I'm unable to insert any data. Every software configuration is in its default state. Here is a code snippet I'm using to insert data.
```
> const Influx = require('influx');
undefined
> const influx = new Influx.InfluxDB('http://[::1]:8086/');
undefined
> const influx_dbname = 'po';
undefined
> influx.createDatabase(influx_dbname);
Promise { <pending> }
> influx.createRetentionPolicy('_inf', {database: influx_dbname, duration: 'inf', replication: 1, default: 1});
Promise { <pending> }
> serial = 22
22
> f = {a :3 }
{ a: 3 }
influx.writePoints([
...   {
.....     measurement: '_' + serial.toString(),
.....     fields: f
.....   }
... ], {
.....   database: influx_dbname,
.....   retentionPolicy: '_inf',
.....   precision: 'ms'
..... });
Promise { <pending> }
```

```
Connected to http://localhost:8086 version 1.3.2
InfluxDB shell version: 1.3.2
> use po
Using database po
> show measurements
name: measurements
name
----
_22
> select * from _22
> insert _22 a=2
> select * from _22
name: _22
time                a
----                -
1502726970385536299 2
```
As you can see I can insert data throug CLI, but not by using `writePoints`. I have tried also with `writePoints`, but with no success. `tcpdump` responses are correct: 204 No Content, but the difference between nodejs and CLI request, is consistency flag CLI is using, on the otherhand nodejs passes rp; username, password although they're not required.

Moreover, reading from InfluxDB works by using nodejs.

If I delete (skip) retentionPolicy in writePoints, everything works. InfluxDB knows it:
```
> SHOW RETENTION POLICIES
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
autogen 0s       168h0m0s           1        true
_inf    0s       168h0m0s           1        false
```

**Comment by brainsea** [comment] 2017-08-24 12:00
Try `select * from po._ inf._ 22`. I guess the issue is due to the missing of retention policy name.

**Comment by connor4312** [comment] 2017-08-30 04:15
@brainsea's answer is correct; you need to explicitly specify the retention policy you're querying from if it's not a default policy. A little annoying, I know, but it makes sense from Influx's data model 😄 

Closing this for now, please reopen / comment if you run into any further issues!

**Closed by connor4312** 2017-08-30 04:15 UTC
Labels: question
