### ISSUE TITLE
Select type of field

### ISSUE THREAD

**Issue by Schaeff** [node-influx/node-influx#87] opened 2015-07-23 13:54 UTC
Hi!

First, thanks to all contributors for developing this great adapter.

I'm a bit confused about field types in InfluxDB 0.9.x:
Type of a given field is determined dynamically according to the type of the first value inserted.
Let's say I have a set of floats that can possibly have no decimal part (for example 1.0, that is 1 in javascript) and I want to store them. Depending on whether the first value I insert has a decimal part or not, the field's type will be Float or Integer, and only that type will be allowed for the next writes.
Using toFixed to have only floats will generate a string and force the field to have String type, which is not what I want.

Am I missing something? How would you enable storing any javascript Number instance in a given field of type Float?

Cheers

**Comment by nichdiekuh** [comment] 2015-07-23 14:13
That's a good question. I'm not sure whether this should be fixed on our side, or in the influxdb API.Since PR #81 from @mrenz node-influx checks whether a value is a string or not.
I currently don't see a way to force sending a decimal point, without ending up with a string, but I consider this as a serious issue which needs to be solved soon.
I'll think about this. Perhaps someone else has a good idea to solve this.

**Comment by Schaeff** [comment] 2015-07-23 15:25
The solutions I see:

- Add 0.000000001 to every value to make sure javascript includes a decimal part. But that's kind of hacky.
- Specify an optional type in the node-influx writes, because node-influx can't guess if 1 is 1 or is actually 1.0, then use toFixed to generate floats that influx will accept. If no type is given, trust influxDB to accept the write or not, and determine the field's type if it's the first write
- Make all numeric fields Float, but that doesn't expose the whole influxDB API
- Ask influxDB to change it's dynamic type policy or at least allow to bypass it. But unlike javascript most languages have different types for numbers, so influxDB is likely to prefer relying on those.

**Comment by jprichardson** [comment] 2015-07-29 04:33
@Schaeff excellent point. `node-influx` is definitely broken. Specifically the `_prepareValues` function. 

For users of this library, a short-term workaround could be to override `Number.prototype.toString()` to always return a number with precision (i.e. not an integer) - this is not a good long-term solution though.

Now for a solution for this library, it'd seem the best way would be to allow types. `integer` or `float` and if it's `float`, maybe use [`Decimal.js`](http://mikemcl.github.io/decimal.js/) to get the precision.  Or if simplicity is preferred, maybe allow the user to pass in a conversion function when `_prepareValues` encounters a `Number`.

**Comment by jprichardson** [comment] 2015-07-29 19:28
Related: https://github.com/influxdb/influxdb/issues/3479

**Comment by nichdiekuh** [comment] 2015-07-29 19:34
Am 29.07.2015 um 21:28 schrieb JP Richardson:
> Related: influxdb/influxdb#3479
> <https://github.com/influxdb/influxdb/issues/3479>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/node-influx/node-influx/issues/87#issuecomment-126068042>.
> 

Thanks for the heads up!

**Comment by connor4312** [comment] 2016-09-25 14:52
Duplicate of https://github.com/node-influx/node-influx/issues/190

**Closed by connor4312** 2016-09-25 14:52 UTC
